# https://taskfile.dev

version: "3"

vars:
  SCRIPT_DIR: scripts
  WEB_SECURITY_GROUP_ID:

tasks:
  build:
    generates:
      - "{{.SCRIPT_DIR}}/toggle"
    sources:
      - main.go
    desc: Build, store binary in scripts directory
    cmds:
      - go build -o {{.SCRIPT_DIR}}/toggle main.go
    silent: false

  open:
    desc: Open the ssh port
    deps:
      - build
    cmds:
      - cd {{.SCRIPT_DIR}} && ./toggle open
    silent: true

  close:
    desc: close the ssh port
    deps:
      - build
    cmds:
      - cd {{.SCRIPT_DIR}} && ./toggle close
    silent: true

  list:
    desc: close the ssh port
    deps:
      - build
    cmds:
      - cd {{.SCRIPT_DIR}} && ./toggle list
    silent: true

  create:
    desc: Create the stack
    cmds:
      - aws cloudformation deploy --stack-name toggle --template-file cfn-template.yaml
    silent: true

  delete:
    desc: Delete the stack
    cmds:
      - aws cloudformation delete-stack --stack-name toggle
    silent: true
